name: build docker image
run-name: ${{ github.actor }} is building jupyterhub
on:
  push:
    branches:
      - main
    paths:
      - hub/**
jobs:
  build_base_and_prod:
    name: build base and image
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - env:
        JUPYTERHUB_TAG: "3.0.0-0.dev.git.6175.hf9af31a3"
      run: |
        docker build -t gfeldman8/hub-k8s:${JUPYTERHUB_TAG} \
            --build-arg JUPYTERHUB_TAG=${JUPYTERHUB_TAG} \
            -f hub/Dockerfile \
            hub/