name: build docker image
run-name: ${{ github.actor }} is building jupyterhub
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build_singleuser.yaml
      - images/singleuser/**
jobs:
  build_base_and_prod:
    name: build base and image
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: |
        cd images/singleuser/
        docker run --rm --volume="$PWD:/io" --workdir=/io --user=root python:3.11-bullseye sh -c 'pip install pip-tools==6.* && pip-compile --resolver=backtracking --upgrade'
        docker build -t gfeldman8/jupyterhub-k8s-singleuser:latest \
            ./
        docker push  gfeldman8/jupyterhub-k8s-singleuser:latest